### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by FelixBenning** [eike-fokken/grazer#158]
It might be possible to use [gooey](https://github.com/chriskiehl/Gooey) for grazer, see

- [Gooey as a universal frontend](https://chriskiehl.com/article/gooey-as-a-universal-frontend)
- [Packaging as an Executable](https://chriskiehl.com/article/packaging-gooey-with-pyinstaller)

**Comment by eike-fokken** [comment]
Done in #178
