### ISSUE TITLE
Add an easily extendable way to provide default values for components

### ISSUE THREAD

**Issue by eike-fokken** [eike-fokken/grazer#220]
At the moment, some values can be inserted in the individual component jsons by the function
`void supply_overall_values_to_components(nlohmann::json &network_json)`.

The values are hardcoded and must be manually written into that function. Also the json interface in `problem_data.json` is arbitrary from value to value.

This should be streamlined in the following way:
in `problem_data.json`, it should be possible to provide a default component json and the function `void supply_overall_values_to_components(nlohmann::json &network_json)` should go over each entry in the default component, check, whether it is already present and if not add it.

**Comment by FelixBenning** [comment]
In `Pipe.cpp`, `desired_delta_x` and `balancelaw` are made required properties of the json schemas

```cpp
  nlohmann::json Pipe::get_schema() {
    // ...
    Aux::schema::add_required(
        schema, "desired_delta_x", Aux::schema::type::number());
    Aux::schema::add_required(
        schema, "balancelaw", Aux::schema::type::string());
    Aux::schema::add_required(schema, "scheme", Aux::schema::type::string());
  }
```

So I do not yet understand why there need to be defaults.
```cpp
 void supply_overall_values_to_components(nlohmann::json &network_json) {

    // This list way well become longer!
    auto pde_components = {"Pipe"};
    for (auto key : {"desired_delta_x", "balancelaw", "scheme"}) {
      if (network_json.contains(key)) {
        for (auto const &type : pde_components) {
          if (not network_json["topology_json"]["connections"].contains(type)) {
            continue;
          }
          for (auto &pipe :
               network_json["topology_json"]["connections"][type]) {
            if (not pipe.contains(key)) {
              pipe[key] = network_json[key];
            } else {
              std::cout << "Object with id " << pipe["id"]
                        << " has its own value of " << key << std::endl;
            }
          }
        }
      }
    }
```

There is also the [default](https://json-schema.org/understanding-json-schema/reference/generic.html) keyword in json schemas - that might be possibly useful?

**Comment by FelixBenning** [comment]
Ah, I think the defaults depend on the the problem, so they can not be hardcoded into the json schema of the components, right? Then things get a bit trickier:

1. Json Schemas should be helpful when typing up the topology.json etc. so these properties should not be required if they are not and have defaults
2. the defaults are not available statically

But since the schema generator is handed a directory (which is supposed to be populated with a `schemas` subfolder), we could probably read out these defaults from the `problem.json` at schema generation to populate the defaults. That still requires loading the `topology.json` with the schema to read out the defaults from the schema

**Comment by eike-fokken** [comment]
Defaults are per problem.
Have a look in data/stochastic/problem/problem_data.json
There values for theta_P and some other parameters are given. Also a balance law and a scheme.

This is for convenience so you dont have to provide the same value for every element. But different values could still be provided in the topology.json, if not all components have the same value.

**Comment by eike-fokken** [comment]
Done in #222
